bot:
  name: "ValutesRateBot"
  token: "1259858094:AAG38xWzr7ghdrsok4-CGnxs41jl8vGyXOE"
proxy:
  host: "127.0.0.1"
  port: 9150
  type: SOCKS4

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){yellow} %clr([%thread]){blue} %-5level %clr(%logger{36}){magenta} - %msg%n"
    file: "%d{HH:mm:ss.SSS} %-4relative [%thread] %-5level %logger{35} - %msg%n"
  level:
    ru.dexsys.TelegramBot: info
  group:
    spring: org.springframework
    apache: org.apache.catalina, org.apache.tomcat, org.apache.coyote

spring:
  output:
    ansi:
      enabled: detect