bot:
  name: "ValutesRateBot"
  token: "1259858094:AAG38xWzr7ghdrsok4-CGnxs41jl8vGyXOE"
proxy:
  host: "127.0.0.1"
  port: 9150
  type: SOCKS4

spring:
  profiles:
    active: dev
  main:
    banner-mode: console

logging:
  level:
    org.springframework: error
    org.hibernate: error
    org.apache: error
    com.netflix: error
    com.zaxxer: error
    ru.dexsys.TelegramBot: info
